export default {
  primary: '#ff6348',
  ligth: '#f1f2f6',
  dark: '#2f3542',
  gray: '#dfe4ea',
  graffiti: '#9ECBCB',
  card: '#e6fefe',
  type: {
    colors: {
      fire: '#FDDFDF',
      grass: '#DEFDE0',
      electric: '#FCF7DE',
      water: '#DEF3FD',
      ground: '#f4e7da',
      rock: '#d5d5d4',
      fairy: '#fceaff',
      poison: '#98d7a5',
      bug: '#f8d5a3',
      dragon: '#97b3e6',
      psychic: '#eaeda1',
      flying: '#F5F5F5',
      fighting: '#E6E0D4',
      normal: '#F5F5F5',
    },
  },
}
